version: '3'

tasks:
  dev:
    desc: Run backend and frontend in dev mode
    cmds:
      - task backend:dev &
      - task frontend:dev
    silent: true

  backend:dev:
    dir: backend
    cmds:
      - air

  frontend:dev:
    dir: frontend
    cmds:
      - bun run dev --host 0.0.0.0
